### ISSUE TITLE
Long error / time out error when trying to search for a movie 

### ISSUE THREAD

**Issue by rivkxx** [JDALab/mov-cli-films#8] opened 2024-04-02 13:35 UTC
Platform- Ubuntu 22.04.4

When using the regular mov-cli -s films <search> command, it gives me a long error message as follows-

```
Traceback (most recent call last):
  File "/home/rick/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/rick/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/rick/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/home/rick/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/home/rick/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/home/rick/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/home/rick/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/home/rick/.local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/rick/.local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout: timed out
```

**Comment by r3tr0ananas** [comment] 2024-04-03 18:32
Time outs are likely not the plugins fault.

Are there more error messages, like where it timed out?

**Comment by THEGOLDENPRO** [comment] 2024-04-03 20:25
Can you run with the `--debug` flag and give use the full output of that.

**Comment by rivkxx** [comment] 2024-04-04 13:42
Here is what showed up when i tried again

The above exception was the direct cause of the following exception:

`Traceback (most recent call last):
  File "/home/rick/.local/bin/mov-cli", line 8, in <module>
    sys.exit(app())
  File "/home/rick/.local/lib/python3.10/site-packages/mov_cli/cli/__main__.py", line 133, in app
    uwu_app() # Wait whaaaaa.
  File "/home/rick/.local/lib/python3.10/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/home/rick/.local/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/rick/.local/lib/python3.10/site-packages/typer/core.py", line 721, in main
    return _main(
  File "/home/rick/.local/lib/python3.10/site-packages/typer/core.py", line 225, in _main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/rick/.local/lib/python3.10/site-packages/typer/main.py", line 685, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/rick/.local/lib/python3.10/site-packages/mov_cli/cli/__main__.py", line 85, in mov_cli
    choice = search(query, auto_select, chosen_scraper, config.fzf_enabled)
  File "/home/rick/.local/lib/python3.10/site-packages/mov_cli/cli/search.py", line 36, in search
    choice = prompt(
  File "/home/rick/.local/lib/python3.10/site-packages/mov_cli/cli/ui.py", line 62, in prompt
    is_just_one, choices = is_it_just_one_choice(choices)
  File "/home/rick/.local/lib/python3.10/site-packages/mov_cli/cli/ui.py", line 42, in is_it_just_one_choice
    for index, _ in enumerate(choices):
  File "/home/rick/.local/lib/python3.10/site-packages/mov_cli/cli/search.py", line 38, in <genexpr>
    choices = (choice for choice in search_results),
  File "/home/rick/.local/lib/python3.10/site-packages/mov_cli_films/vidsrcto/scraper.py", line 36, in search
    embed_response = self.__get_embed(search_result, EpisodeSelector())
  File "/home/rick/.local/lib/python3.10/site-packages/mov_cli_films/vidsrcto/scraper.py", line 98, in __get_embed
    return self.http_client.get(url)
  File "/home/rick/.local/lib/python3.10/site-packages/mov_cli/http_client.py", line 55, in get
    response = self.__httpx_client.get(
  File "/home/rick/.local/lib/python3.10/site-packages/httpx/_client.py", line 1054, in get
    return self.request(
  File "/home/rick/.local/lib/python3.10/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/rick/.local/lib/python3.10/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/home/rick/.local/lib/python3.10/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/rick/.local/lib/python3.10/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/rick/.local/lib/python3.10/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/home/rick/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/rick/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: timed out`

here's what shows up when i use the `--debug` flag

`[DEBUG] (mov_cli) - Config -> {'version': 1, 'player': 'mpv', 'debug': True, 'ui': {'fzf': True}, 'plugins': {'test': 'mov-cli-test', 'films': 'mov-cli-films', 'youtube': 'mov-cli-youtube'}}
`

**Comment by THEGOLDENPRO** [comment] 2024-04-04 13:49
There should have been more debug messages than that, can you send the full terminal output also maybe dump it here: https://paste.nextcord.dev/

**Comment by THEGOLDENPRO** [comment] 2024-04-04 13:50
so far just seems like a connection problem from your end but I could be wrong so I'll need more logs.

**Comment by rivkxx** [comment] 2024-04-04 13:57
https://paste.nextcord.dev/?id=1712238868174890

**Comment by rivkxx** [comment] 2024-04-04 14:04
I don't think it's a network connection problem because ive switched my wifi around and it doesn't work either.

**Comment by THEGOLDENPRO** [comment] 2024-04-04 14:05
> https://paste.nextcord.dev/?id=1712238868174890

Okay for this particular traceback it seems like the update checker is failing for some reason for you and the exception wasn't handled. I'll quickly patch this.

**Comment by THEGOLDENPRO** [comment] 2024-04-04 14:49
@rivkxx the latest update should fix the update checker problem. Can you try version `4.2.10` out.

**Comment by rivkxx** [comment] 2024-04-04 16:55
I just updated it, but i seem to be getting the same error
The scraper seems to be working for youtube but its only the films that it isn't working with.
https://paste.nextcord.dev/?id=1712249649500733

**Comment by THEGOLDENPRO** [comment] 2024-04-04 17:06
Btw when I mentioned full terminal output I meant the entire output with ``--debug`` from the line you executed the command to end. Sorry for not being clear, I'm going to need a lot more info than the traceback to help determine the cause.

**Comment by THEGOLDENPRO** [comment] 2024-04-18 00:07
Closing this as it hasn't been active for 2 weeks and this strongly sounds like a user connection based issue. We can re-open it if you strongly believe it's not.

**Closed by THEGOLDENPRO** 2024-04-18 00:07 UTC
